// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'event.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_BackendMidaEvent _$BackendMidaEventFromJson(Map<String, dynamic> json) =>
    _BackendMidaEvent(
      id: json['id'] as String?,
      clientId: json['mandant'] as String?,
      date: json['datum'] as String?,
      title: json['titel'] as String?,
      description: json['beschreibung'] as String?,
      location: json['ort'] as String?,
      groupId: json['akid'] as String?,
      time: json['zeit'] as String?,
      numberOfDays: json['anzahltage'] as String?,
      overlapping: json['ueberlappend'] as String?,
      userId: json['userid'] as String?,
      contactName: json['kontakt'] as String?,
      contactEmail: json['kontaktemail'] as String?,
      contactPhone: json['kontakttelefon'] as String?,
      contactStreet: json['kontaktstrasse'] as String?,
      contactCity: json['kontaktort'] as String?,
      contactFax: json['kontaktfax'] as String?,
      maxParticipants: json['maxpersonen'] as String?,
      image: json['bild'] as String?,
      attachments: json['attachments'] as String?,
      reminderDaysBefore: json['remindertagezuvor'] as String?,
      reminderTarget: json['remindertarget'] as String?,
      costMember: json['kostenmitglied'] as String?,
      costGuest: json['kostenfremd'] as String?,
      costCompanion: json['kostenbegleitung'] as String?,
      cost: json['kosten'] as String?,
      publicType: json['oeffentlich'] as String?,
      visibleFrom: json['sichtbarab'] as String?,
      reminderSent: json['remindersent'] as String?,
      registrationEmail: json['anmeldemail'] as String?,
      registrationEmailContent: json['anmeldemailcontent'] as String?,
      registrationUserPublic: json['anmeldunguserpublic'] as String?,
      type: json['typ'] as String?,
      registrationStart: json['anmeldebeginn'] as String?,
      registrationDeadline: json['anmeldeschluss'] as String?,
      colorPrimary: json['vfarbe'] as String?,
      colorSecondary: json['hfarbe'] as String?,
      specialDate: json['datumspezial'] as String?,
      visibilityType: json['sichtbar'] as String?,
      deregistrationDeadline: json['abmeldeschluss'] as String?,
      maxCompanions: json['maxbegleiter'] as String?,
      workflowStatus: json['workflowstatus'] as String?,
      workflowUserId: json['workflowuserid'] as String?,
      groupId2: json['akid2'] as String?,
      followUp: json['nachlese'] as String?,
      reminderDaysBefore2: json['remindertagezuvor2'] as String?,
      reminderTarget2: json['remindertarget2'] as String?,
      waitlist: json['warteliste'] as String?,
      paymentMethod: json['zahlungsweise'] as String?,
      accessControlList: json['acl'] as String?,
      registrationConfirmationEmail:
          json['anmeldebestaetigungsmail'] as String?,
      seriesEventId: json['serienveranstaltungid'] as String?,
      imageCount: json['bilder'] as String?,
      notes: json['bemerkung'] as String?,
      modified: json['modified'] as String?,
      kvp: json['kvp'] as String?,
      currency: json['currency'] as String?,
      visibilityAssociation: json['sichtbarverband'] as String?,
      course: json['kurs'] as String?,
      assembly: json['versammlung'] as String?,
      rv: json['rv'] as String?,
      abbreviation: json['kuerzel'] as String?,
      organization: json['verein'] as String?,
      registrationCount: json['anmeldungen'] as String?,
      descriptionTeaser: json['beschreibungteaser'] as String?,
      freeSlots: json['freieplaetze'] as String?,
      weekdayDate: json['wotagdatum'] as String?,
      trafficLight: json['ampel'] as String?,
      discountInfo: json['rabattinfo'] as String?,
      link: json['link'] as String?,
      url: json['url'] as String?,
      clientEventId: json['idmandant'] as String?,
    );

Map<String, dynamic> _$BackendMidaEventToJson(_BackendMidaEvent instance) =>
    <String, dynamic>{
      'id': instance.id,
      'mandant': instance.clientId,
      'datum': instance.date,
      'titel': instance.title,
      'beschreibung': instance.description,
      'ort': instance.location,
      'akid': instance.groupId,
      'zeit': instance.time,
      'anzahltage': instance.numberOfDays,
      'ueberlappend': instance.overlapping,
      'userid': instance.userId,
      'kontakt': instance.contactName,
      'kontaktemail': instance.contactEmail,
      'kontakttelefon': instance.contactPhone,
      'kontaktstrasse': instance.contactStreet,
      'kontaktort': instance.contactCity,
      'kontaktfax': instance.contactFax,
      'maxpersonen': instance.maxParticipants,
      'bild': instance.image,
      'attachments': instance.attachments,
      'remindertagezuvor': instance.reminderDaysBefore,
      'remindertarget': instance.reminderTarget,
      'kostenmitglied': instance.costMember,
      'kostenfremd': instance.costGuest,
      'kostenbegleitung': instance.costCompanion,
      'kosten': instance.cost,
      'oeffentlich': instance.publicType,
      'sichtbarab': instance.visibleFrom,
      'remindersent': instance.reminderSent,
      'anmeldemail': instance.registrationEmail,
      'anmeldemailcontent': instance.registrationEmailContent,
      'anmeldunguserpublic': instance.registrationUserPublic,
      'typ': instance.type,
      'anmeldebeginn': instance.registrationStart,
      'anmeldeschluss': instance.registrationDeadline,
      'vfarbe': instance.colorPrimary,
      'hfarbe': instance.colorSecondary,
      'datumspezial': instance.specialDate,
      'sichtbar': instance.visibilityType,
      'abmeldeschluss': instance.deregistrationDeadline,
      'maxbegleiter': instance.maxCompanions,
      'workflowstatus': instance.workflowStatus,
      'workflowuserid': instance.workflowUserId,
      'akid2': instance.groupId2,
      'nachlese': instance.followUp,
      'remindertagezuvor2': instance.reminderDaysBefore2,
      'remindertarget2': instance.reminderTarget2,
      'warteliste': instance.waitlist,
      'zahlungsweise': instance.paymentMethod,
      'acl': instance.accessControlList,
      'anmeldebestaetigungsmail': instance.registrationConfirmationEmail,
      'serienveranstaltungid': instance.seriesEventId,
      'bilder': instance.imageCount,
      'bemerkung': instance.notes,
      'modified': instance.modified,
      'kvp': instance.kvp,
      'currency': instance.currency,
      'sichtbarverband': instance.visibilityAssociation,
      'kurs': instance.course,
      'versammlung': instance.assembly,
      'rv': instance.rv,
      'kuerzel': instance.abbreviation,
      'verein': instance.organization,
      'anmeldungen': instance.registrationCount,
      'beschreibungteaser': instance.descriptionTeaser,
      'freieplaetze': instance.freeSlots,
      'wotagdatum': instance.weekdayDate,
      'ampel': instance.trafficLight,
      'rabattinfo': instance.discountInfo,
      'link': instance.link,
      'url': instance.url,
      'idmandant': instance.clientEventId,
    };

_MidaEvent _$MidaEventFromJson(Map<String, dynamic> json) => _MidaEvent(
      id: (json['id'] as num).toInt(),
      clientId: (json['clientId'] as num?)?.toInt(),
      startDateAndTime: DateTime.parse(json['startDateAndTime'] as String),
      endDateAndTime: DateTime.parse(json['endDateAndTime'] as String),
      title: json['title'] as String,
      description: json['description'] as String?,
      location: json['location'] as String?,
      groupId: (json['groupId'] as num?)?.toInt(),
      time: json['time'] as String?,
      numberOfDays: (json['numberOfDays'] as num?)?.toInt(),
      contactName: json['contactName'] as String?,
      contactEmail: json['contactEmail'] as String?,
      maxParticipants: (json['maxParticipants'] as num?)?.toInt(),
      image: json['image'] as String?,
      attachments: (json['attachments'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList(),
      costMember: (json['costMember'] as num?)?.toDouble(),
      costGuest: (json['costGuest'] as num?)?.toDouble(),
      costCompanion: (json['costCompanion'] as num?)?.toDouble(),
      cost: json['cost'] as String?,
      publicType: (json['publicType'] as num?)?.toInt(),
      type: (json['type'] as num?)?.toInt(),
      registrationStart: json['registrationStart'] == null
          ? null
          : DateTime.parse(json['registrationStart'] as String),
      registrationDeadline: json['registrationDeadline'] == null
          ? null
          : DateTime.parse(json['registrationDeadline'] as String),
      visibilityType: (json['visibilityType'] as num?)?.toInt(),
      deregistrationDeadline: json['deregistrationDeadline'] == null
          ? null
          : DateTime.parse(json['deregistrationDeadline'] as String),
      maxCompanions: (json['maxCompanions'] as num?)?.toInt(),
      seriesEventId: (json['seriesEventId'] as num?)?.toInt(),
      visibilityAssociation: (json['visibilityAssociation'] as num?)?.toInt(),
      rv: json['rv'] as bool?,
      abbreviation: json['abbreviation'] as String?,
      organization: json['organization'] as String?,
      registrationCount: (json['registrationCount'] as num?)?.toInt(),
      freeSlots: json['freeSlots'] as String?,
      link: json['link'] as String?,
      baseUrl: json['baseUrl'] as String,
      clientEventId: json['clientEventId'] as String?,
    );

Map<String, dynamic> _$MidaEventToJson(_MidaEvent instance) =>
    <String, dynamic>{
      'id': instance.id,
      'clientId': instance.clientId,
      'startDateAndTime': instance.startDateAndTime.toIso8601String(),
      'endDateAndTime': instance.endDateAndTime.toIso8601String(),
      'title': instance.title,
      'description': instance.description,
      'location': instance.location,
      'groupId': instance.groupId,
      'time': instance.time,
      'numberOfDays': instance.numberOfDays,
      'contactName': instance.contactName,
      'contactEmail': instance.contactEmail,
      'maxParticipants': instance.maxParticipants,
      'image': instance.image,
      'attachments': instance.attachments,
      'costMember': instance.costMember,
      'costGuest': instance.costGuest,
      'costCompanion': instance.costCompanion,
      'cost': instance.cost,
      'publicType': instance.publicType,
      'type': instance.type,
      'registrationStart': instance.registrationStart?.toIso8601String(),
      'registrationDeadline': instance.registrationDeadline?.toIso8601String(),
      'visibilityType': instance.visibilityType,
      'deregistrationDeadline':
          instance.deregistrationDeadline?.toIso8601String(),
      'maxCompanions': instance.maxCompanions,
      'seriesEventId': instance.seriesEventId,
      'visibilityAssociation': instance.visibilityAssociation,
      'rv': instance.rv,
      'abbreviation': instance.abbreviation,
      'organization': instance.organization,
      'registrationCount': instance.registrationCount,
      'freeSlots': instance.freeSlots,
      'link': instance.link,
      'baseUrl': instance.baseUrl,
      'clientEventId': instance.clientEventId,
    };
